require:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/LambdaCall:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: [array, hash]
  Exclude:
    - "test/**/*"

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Max: 23

Metrics/CyclomaticComplexity:
  Max: 8

Lint/MissingSuper:
  Enabled: false
